### ISSUE TITLE
Spelling error in taxonomie

### ISSUE THREAD

**Issue by lindemann09** [ShareStats/Statistics_Taxonomy#6]
Hi @ShKlinkenberg,

There is a spelling error in the tags. Instead of "_Interpretating graph/output_" it should be "_Interpreting graph/output_". (see https://github.com/ShareStats/Statistics_Taxonomy/blob/main/source/Taxonomie%20ShareStats%20versie%2017%20maart%202021.xlsx?raw=true) As a consequence, the error also on the website and our app and the misspelled tags is probably already in many item of the sharestats database. How shall we deal with this error?

Oliver

**Comment by ShKlinkenberg** [comment]
Solved 😊

Thanks for letting me know.

From: Oliver Lindemann ***@***.***>
Date: Wednesday, 20 April 2022 at 14:42
To: ShareStats/Statistics_Taxonomy ***@***.***>
Cc: Sharon Klinkenberg ***@***.***>, Mention ***@***.***>
Subject: [ShareStats/Statistics_Taxonomy] Spelling error in taxonomie (Issue #6)

Hi @ShKlinkenberg<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FShKlinkenberg&data=05%7C01%7Cs.klinkenberg%40uva.nl%7Cab15fb65b46b4e08efe308da22cb1d5f%7Ca0f1cacd618c4403b94576fb3d6874e5%7C0%7C0%7C637860553571629816%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=7xQ29xqDEVbK%2Fo5sir%2ByRio5zOQMomrLa4o1E3qAnTw%3D&reserved=0>,

There is a spelling error in the tags. Instead of "Interpretating graph/output" it should be "Interpreting graph/output". (see https://github.com/ShareStats/Statistics_Taxonomy/blob/main/source/Taxonomie%20ShareStats%20versie%2017%20maart%202021.xlsx?raw=true<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FShareStats%2FStatistics_Taxonomy%2Fblob%2Fmain%2Fsource%2FTaxonomie%2520ShareStats%2520versie%252017%2520maart%25202021.xlsx%3Fraw%3Dtrue&data=05%7C01%7Cs.klinkenberg%40uva.nl%7Cab15fb65b46b4e08efe308da22cb1d5f%7Ca0f1cacd618c4403b94576fb3d6874e5%7C0%7C0%7C637860553571629816%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=tKzxienwQZQ7k4ejFvvi7dyvgQEua07Sm6wEFgA0NgU%3D&reserved=0>) As a consequence, the error also on the website and our app and the misspelled tags is probably already in many item of the sharestats database. How shall we deal with this error?

Oliver

**Comment by ShKlinkenberg** [comment]
No to self. Write a script to check if the wrong spelling has been used in the item development and correct it.
